name: Flutter CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze project source
        run: flutter analyze
      - name: Run tests
        run: flutter test
      # Uncomment the following step if you want to build the app
      # - name: Build APK
      #   run: flutter build apk
